version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - backend/.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lunna_tech
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: "exit 0"